/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Airplane() {
  const { nodes, materials } = useGLTF("/plane.glb");

  return (
    <group dispose={null}>
      <mesh
        castShadow
        receiveShadow
        // geometry={nodes.gear_1001.geometry}
        material={materials.texture}
        position={[-4.08, 1.76, 21.925]}
        scale={0.181}
      />
      <mesh
        castShadow
        receiveShadow
        // geometry={nodes.wheel001.geometry}
        material={materials.texture}
        position={[-3.406, 0.734, 21.209]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.574, 0.31, 0.574]}
      />
      <mesh
        castShadow
        receiveShadow
        // geometry={nodes.antenna.geometry}
        material={materials.texture}
        position={[-4.113, 8.019, 13.024]}
        scale={[0.012, 0.149, 0.149]}
      />
      <mesh
        castShadow
        receiveShadow
        // geometry={nodes.fuselage.geometry}
        material={materials.texture}
        position={[-4.112, 5.06, 3.311]}
        scale={2.934}
      />
      <mesh
        castShadow
        receiveShadow
        // geometry={nodes.gear_1.geometry}
        // material={nodes.gear_1.material}
        position={[0.699, 1.76, -0.439]}
        scale={0.181}
      />
      <mesh
        castShadow
        receiveShadow
        // geometry={nodes.box_2.geometry}
        // material={nodes.box_2.material}
        position={[1.029, 3.443, 0.07]}
        rotation={[Math.PI / 2, 0.197, -Math.PI / 2]}
        scale={0.746}
      />
      <mesh
        castShadow
        receiveShadow
        // geometry={nodes.hydraolic.geometry}
        material={materials.texture}
        position={[0.487, 1.798, -0.243]}
        rotation={[0, 0, 0.725]}
        scale={0.068}
      />
      <mesh
        castShadow
        receiveShadow
        // geometry={nodes.wheel.geometry}
        material={materials.texture}
        position={[1.373, 0.734, -0.37]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.574, 0.31, 0.574]}
      />
      <mesh
        castShadow
        receiveShadow
        // geometry={nodes.box_1.geometry}
        material={materials.texture}
        position={[-3.734, 2.328, 22.258]}
        scale={0.538}
      />
      <mesh
        castShadow
        receiveShadow
        // geometry={nodes.aileron.geometry}
        material={materials.texture}
        position={[14.496, 5.522, -6.178]}
        scale={[-0.284, -0.284, -1.863]}
      />
      <mesh
        castShadow
        receiveShadow
        // geometry={nodes.engine.geometry}
        material={materials.texture}
        position={[5.661, 2.761, 8.325]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={1.938}
      />
    </group>
  );
}

useGLTF.preload("/plane.glb");
